import Link from "next/link";
import type { OrderDTO } from "@/services/order-service";
import { CloudinaryImage as Image } from "@/components/CloudinaryImage";
import { formatINR } from "@/utils/format";

export function OrderSummary({ order }: { order: OrderDTO }) {
  return <div>
    <ul className="divide-y divide-light-gray">{order.items.map((item,index) => <li className="flex gap-3 py-4" key={`${item.productId}:${item.variantSku}:${index}`}>{item.image && <span className="relative h-16 w-12 shrink-0 bg-cream"><Image src={item.image} alt="" fill sizes="48px" className="object-cover" /></span>}<div className="min-w-0 flex-1"><p className="text-sm">{item.name}</p>{item.variantSku && <p className="mt-1 text-xs text-muted">{item.variantLabel || item.variantSku}</p>}<p className="mt-1 text-xs text-muted">Quantity {item.qty}</p></div><p className="text-sm">{formatINR(item.totalPrice)}</p></li>)}</ul>
    <dl className="space-y-3 border-t border-light-gray pt-4 text-sm">{[["Subtotal",formatINR(order.subtotal)],["Discount",order.discount > 0 ? `−${formatINR(order.discount)}` : "—"],["Delivery",order.shipping ? formatINR(order.shipping) : "Free"],...(order.tax > 0 ? [["Tax",formatINR(order.tax)]] : [])].map(([label,value]) => <div key={label} className="flex justify-between gap-3"><dt>{label}</dt><dd>{value}</dd></div>)}<div className="flex justify-between border-t border-light-gray pt-4 text-base font-semibold"><dt>{order.paymentStatus === "PAID" ? "Amount paid" : "Total payable"}</dt><dd>{formatINR(order.total)}</dd></div></dl><p className="mt-2 text-xs text-muted">Taxes included in product prices.</p>
  </div>;
}
export function OrderConfirmation({ order, delivery }: { order: OrderDTO; delivery?: string }) {
  return <div className="grid gap-8 lg:grid-cols-2"><div><h2 className="section-title text-3xl">Order confirmed</h2><p className="mt-4 text-sm">Order <strong>{order.id.slice(-8).toUpperCase()}</strong></p><p className="mt-3 text-sm leading-6 text-muted">Your payment has been confirmed and your order is recorded.</p><h3 className="mt-7 text-sm font-semibold">Delivery address</h3><address className="mt-3 text-sm not-italic leading-7">{order.address.fullName}<br />{order.address.addressLine1}{order.address.addressLine2 && <><br />{order.address.addressLine2}</>}<br />{order.address.city}, {order.address.state} {order.address.pincode}<br />{order.address.phone}</address>{delivery && <p className="mt-5 text-sm leading-6 text-muted">{delivery}</p>}<Link href={`/orders/${order.id}`} className="btn-primary mt-6">Track order</Link><Link href="/contact" className="ml-5 inline-block min-h-11 py-3 text-sm underline underline-offset-4">Order support</Link>{order.isGuest && <p className="mt-4 text-xs leading-6 text-muted">Keep this order number. Order tracking is available in this browser for 30 days; contact support if you use another device.</p>}</div><div className="bg-cream p-5 sm:p-7"><OrderSummary order={order} /></div></div>;
}
