import Link from "next/link";
import { getSettings } from "@/services/settings-service";
import type { Metadata } from "next";
import { pageMetadata } from "@/lib/page-seo";
export const metadata: Metadata = pageMetadata("/about", "About SatvaStones | Online Jewellery from Vapi, Gujarat", "SatvaStones is an online-only jewellery business based in Vapi, Gujarat. Explore product details, delivery information and customer support for orders in India.");
export default async function AboutPage() {
  const settings = await getSettings();
  const introduction = <p className="mt-5 max-w-prose text-sm leading-8 text-muted">SatvaStones is an online-only jewellery business based in Vapi, Gujarat, serving customers across India. Browse the collection online and contact our team for product or delivery questions.</p>;
  return <div className="mx-auto w-full max-w-4xl px-4 py-12 sm:px-8 sm:py-16"><p className="eyebrow">Our story</p><h1 className="section-title mt-3 text-4xl sm:text-5xl">About SatvaStones</h1>{introduction}<div className="mt-8 max-w-prose space-y-5 text-sm leading-8 text-muted">{settings.aboutInformation ? settings.aboutInformation.split(/\n\s*\n/).filter(Boolean).map((text,index) => <p key={index} className="whitespace-pre-line">{text}</p>) : <><p>SatvaStones brings together rings, earrings, necklaces, bracelets and more in one jewellery collection.</p><p>Each product page lists the available options, price and product details so you can choose a piece that suits you. Our team can help with questions before or after ordering.</p></>}</div><div className="mt-10 grid gap-6 border-y border-light-gray py-8 sm:grid-cols-3">{[["/shop","Explore the collection","Find your next everyday favourite."],["/shipping","Delivery information","See current shipping charges and delivery details."],["/contact","Talk to us","Ask about a piece or get order support."]].map(([href,title,body]) => <div key={href}><h2 className="text-base font-medium">{title}</h2><p className="mt-3 text-sm leading-6 text-muted">{body}</p><Link href={href} className="mt-4 inline-block min-h-11 py-3 text-sm underline underline-offset-4">{title}</Link></div>)}</div></div>;
}
